# Generated by Django 3.1.5 on 2021-01-20 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('img', models.BinaryField()),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
