# Generated by Django 3.1.5 on 2021-01-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='car',
        ),
    ]
